name = "webhook-connectors"
type = "webpack"
workers_dev = true
account_id = "19cf6826c19fdd5e3fa2d71928122959" # developers.squadcast.workers.dev
compatibility_date = "2022-01-17"

[env.production]
workers_dev = true
account_id = "19cf6826c19fdd5e3fa2d71928122959" # developers.squadcast.workers.dev
route = "https://developers.squadcast.workers.dev/webhook-connectors*"

[site]
bucket = ".docs/public/"
entry-point = ".docs/workers-site"
