name = "developers"
type = "webpack"
account_id = "19cf6826c19fdd5e3fa2d71928122959" # developers.squadcast.workers.dev
workers_dev = true
compatibility_date = "2022-01-17"

[env.production]
workers_dev = true
account_id = "19cf6826c19fdd5e3fa2d71928122959" # developers.squadcast.workers.dev
route = "https://developers.squadcast.workers.dev"

[site]
bucket = "/public"
entry-point = "workers-site"
